declare module "../modules/css/*.css"
declare module "../modules/images/*.svg"
declare module "../modules/images/*.jpg"
declare module "../modules/js/*.ts"
declare module "../images/*.svg"
declare module "../images/*.jpg"