declare module "../modules/css/*.css"
declare module "../modules/images/*.svg"
declare module "../modules/js/*.ts"
declare module "../images/*.svg"
declare module "../modules/html/*.html"
declare module "../html/*.html"